# config/settings.yml

defaults: &defaults
  product_name: "Pindea"
  basic_auth_user: "homer"
  basic_auth_password: "simpson"
    
development:
  <<: *defaults

test:
  <<: *defaults
  
production:
  basic_auth_user: "Eric"
  basic_auth_password: "C@rtman"
  <<: *defaults


# defaults: &defaults
#   cool:
#     saweet: nested settings
#   neat_setting: 24
#   awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>
# 
# development:
#   <<: *defaults
#   neat_setting: 800
# 
# test:
#   <<: *defaults
# 
# production:
#   <<: *defaults