# config/settings.yml

defaults: &defaults
    product_name: "Pindea"
    
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults

# defaults: &defaults
#   cool:
#     saweet: nested settings
#   neat_setting: 24
#   awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>
# 
# development:
#   <<: *defaults
#   neat_setting: 800
# 
# test:
#   <<: *defaults
# 
# production:
#   <<: *defaults